name: Deploy Next.js to EC2 via ECR

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3️⃣ Login ECR
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin 508137168655.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # 4️⃣ Build Docker image (trên GitHub Actions)
      - name: Build Docker image
        run: docker build -t next-app .

      # 5️⃣ Tag image cho ECR
      - name: Tag Docker image
        run: docker tag next-app:latest 508137168655.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/next-app:latest

      # 6️⃣ Push image lên ECR
      - name: Push Docker image to ECR
        run: docker push 508137168655.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/next-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Login ECR
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
            docker login --username AWS --password-stdin 508137168655.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            # Pull image
            docker pull 508137168655.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/next-app:latest

            # Stop & remove old container (nếu có)
            docker stop nextjs-container || true
            docker rm nextjs-container || true

            # Run container mới
            docker run -d -p 3000:3000 --name nextjs-container 508137168655.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/next-app:latest